<script type="text/javascript" src="<?= $this->baseUrl() . '/resources/js/library/jquery.iframe-auto-height.plugin.1.5.0.min.js' ?>"></script>
<h1><?= $this->deal_details['deal_title'] ?></h1><br/>
<iframe class="auto-height" width="1025px" src="/deals/details/deal_id/<?= $this->deal_id ?>/s/true"></iframe>
<script>
	$(document).ready(function(){
		jQuery('.auto-height').iframeAutoHeight({});
	});
</script>