<div class="content-box"><!-- Start Content Box -->
		
	<div class="content-box-content">
		
		<div class="tab-content default-tab" id="tab1"> <!-- This is the target div. id must match the href of this div's tab -->
			<?php if ($this->user_deals['deals']): ?>
				<div id="sidebar">
					<div id="sidebar-wrapper"> <!-- Sidebar with logo and menu -->
						<h3 id="sidebar-title">Filters</h3>
						<ul id="main-filter">  <!-- Accordion Menu -->
							<li> 
								<a href="#" class="filter-group current"> <!-- Add the class "current" to current menu item -->
									Companies
								</a>
								<ul id="publisher-filter">
								</ul>
							</li>
	<!--
							<li>
								<a href="#" class="filter-group">
									Discount %
								</a>
								<ul>
									<li>
										<div id="discount-per-slider"></div>
										<div id="discount-slider-values"></div>
									</li>
								</ul>
							</li>
							
							<li>
								<a href="#" class="filter-group">
									Expiry Date
								</a>
								<ul>
								</ul>
							</li>
							
							<li>
								<a href="#" class="filter-group">
									Categories
								</a>
								<ul id="category-filter">
								</ul>
							</li>
	-->
						</ul> <!-- End #main-filter -->
						
					</div>
				</div> <!-- End #sidebar -->
				<div id="deals-sort-select-container">
					Organize by: 
					<select>
						<?php
							foreach ($this->sort_params as $key => $sort_param) {
								echo '<option value="sort-param-'.$key.'">'.$sort_param.'</option>';
							}
						?>
					</select>
				</div>
				<div id="deals-container">
					<div id="deals-filter-overlay" style="display: none;"><img src="<?= $this->baseUrl() ?>/resources/images/loading.gif" alt="Loading" /> Applying Filter...</div>
					<div id="deals-loading"><img src="<?= $this->baseUrl() ?>/resources/images/loading.gif" alt="Loading" /> Loading Deals...</div>
					<div id="filter-no-results" style="display: none;">No deals matching your filter conditions was found.</div>
				</div>
				<div id="load-more-deals-container">
					<a class="button white" id="load-more-deals">Load more..</a>
			 	</div>
				<script type="text/javascript">
					Application.__user_deals = <?= json_encode( $this->user_deals ); ?>;
					Application.__deals_obj = new Deals();
					Application.__deals_obj.init( Application.__user_deals );
				</script>
			<?php else: ?>
				<p id="no-deals-msg-container">You currently do not have any deals.</p>
				<p class="tip-container"><img src="/resources/images/tip.png" alt="Tip" /><span class="tip-message">Deallr automatically creates an email address for you to register for deals. This enables you to free your personal inbox and have a dedicated deals address. Once you register using @deallr.com address, those deals will automatically appear in your account here.</span></p>
		 	<?php endif; //user_deals ?>
			<div class="clear"></div>
		</div> <!-- End #tab1 -->
				
	</div> <!-- End .content-box-content -->
	
</div> <!-- End .content-box -->