<div class="content-box"><!-- Start Content Box -->
	
	<div class="content-box-header">
		
		<ul class="content-box-tabs">
			<li><a href="#tab1" class="default-tab">My Deals</a></li> <!-- href must be unique and match the id of target div -->
			<li><a href="#tab2">Popular</a></li>
		</ul>
		
		<div class="clear"></div>
		
	</div> <!-- End .content-box-header -->
	
	<div class="content-box-content">
		
		<div class="tab-content default-tab" id="tab1"> <!-- This is the target div. id must match the href of this div's tab -->
			<div id="sidebar">
				<div id="sidebar-wrapper"> <!-- Sidebar with logo and menu -->
					<h3 id="sidebar-title">Filters</h3>
					<ul id="main-filter">  <!-- Accordion Menu -->
						<li> 
							<a href="#" class="filter-group current"> <!-- Add the class "current" to current menu item -->
								Companies
							</a>
							<ul id="publisher-filter">
							</ul>
						</li>
						
						<li>
							<a href="#" class="filter-group">
								Discount %
							</a>
							<ul>
								<li>
									<div id="discount-per-slider"></div>
									<div id="discount-slider-values"></div>
								</li>
							</ul>
						</li>
						
						<li>
							<a href="#" class="filter-group">
								Expiry Date
							</a>
							<ul>
							</ul>
						</li>
						
						<li>
							<a href="#" class="filter-group">
								Categories
							</a>
							<ul id="category-filter">
							</ul>
						</li>
					</ul> <!-- End #main-filter -->
					
				</div>
			</div> <!-- End #sidebar -->
			<div id="deals-container">
				<div id="deals-filter-overlay" style="display: none;"><img src="<?= $this->baseUrl() ?>/resources/images/loading.gif" alt="Loading" /> Applying Filter...</div>
				<div id="deals-loading"><img src="<?= $this->baseUrl() ?>/resources/images/loading.gif" alt="Loading" /> Loading Deals...</div>
				<div id="filter-no-results" style="display: none;">No deals matching your filter conditions was found.</div>
				<script type="text/javascript">
					Application.__user_deals = <?= json_encode( $this->user_deals ); ?>;
					Application.__deals_obj = new Deals();
					Application.__deals_obj.init( Application.__user_deals );
				</script>
			</div>
			<div class="clear"></div>
		</div> <!-- End #tab1 -->
		
		<div class="tab-content" id="tab2">
		
			<form action="" method="post">
				
				<fieldset> <!-- Set class to "column-left" or "column-right" on fieldsets to divide the form into columns -->
					<p>
						<label>COMING SOON</label>
					</p>
				</fieldset>
				
				<div class="clear"></div><!-- End .clear -->
				
			</form>
			
		</div> <!-- End #tab2 -->        
		
	</div> <!-- End .content-box-content -->
	
</div> <!-- End .content-box -->