<h3>What is Deallr?</h3>
<p>
Deallr wants to solve two main problems. Remove deal and coupon clutter from your email and to help you find the right deal when you want it.
Deallr is built on the belief that email is not made for discovering and browsing content and your favorite deals should not get lost under the large numbers of deals and coupons.</p>
<br/>
<h3>What do we do?</h3>
<p>
We have built an innovative technology to identify and crawl only deal and coupon emails from your inbox. We extract the important parts from these emails like deal value, expiration date, free shipping information etc and show you these deals on an intuitive UI.
We have created several very useful filters for you so that you can easily separate out the best deals for you. We learn your taste over time so that can we prioritize your deal feed as per your taste.
<br/>
Each user gets an email address that they can use to subscribe to their favorite retailers and daily deals services and never share your personal email. You can add deals to a wallet so that you can take an action on it later.
</p>
<br/>
<h3>Who are we?</h3>
<p>
We are a team of engineers with tons of experience in building large-scale consumer services. Collectively we excel in web, big data, machine learning, and email. We helped build some top companies in valley.
<br/>
We love our clean inbox and we are always looking out for a great deal since our wish list is never ending.
</p>