<h2>Contact</h2>
<h6>Feedback</h6>
<p>Give us feedback! We'd love to know what you love (and hate) about Deallr. <br/>Are we missing your favorite retailer or deal provider? Click "Feedback" button on the left.</p>
<br/><br/>
<h6>Retailers</h6>
<p>Are you a retailer interested in seeing your deals listed? Contact <a href="mailto:sales@deallr.com">sales@deallr.com</a></p>
<br/><br/>
<h6>Advertisers</h6>
<p>Interested in advertising on Deallr? Contact <a href="mailto:sales@deallr.com">sales@deallr.com</a></p>
<br/><br/>
<h6>Press</h6>
<p>Are you a member of the press who wants to know more about the Deallr phenomenon? Contact <a href="mailto:pr@deallr.com">pr@deallr.com</a></p>
<br/><br/>
<h6>Support</h6>
<p>Email us at <a href="mailto:support@deallr.com">support@deallr.com</a></p>
<br/><br/>
<h6>Other</h6>
<p>For all other inquiries, send an email to <a href="mailto:contact@deallr.com">contact@deallr.com</a></p>
<br/><br/>