<h2>Privacy Policy</h2>
<p>
	This policy covers how Deallr treats Personally Identifiable Information ("PII") and other information that Deallr collects in connection with our services. Deallr considers PII to be information that can be traced directly back to and identifies an individual, such as name, address, email address, and/or phone number. We do not consider PII to include information that has been anonymized so that it does not allow a third party to easily identify a specific individual.
	By using this website and accepting the Terms of Service, you agree to this Privacy Policy. IF YOU DO NOT AGREE TO THIS PRIVACY POLICY, YOU MAY NOT USE THE WEBSITE OR SERVICES.
</p>
<ol>
	<li>
		<br/>
		<h6>Scope of privacy policy<h6>
		<p>
			This Privacy Policy applies to PII and other information collected by Deallr through your use of Deallr or Deallr ‘s services and does not apply to any other information collected by Deallr through other means. When you navigate away from our website to websites controlled by third parties, you leave the Deallr website, at which point our Privacy Policy no longer applies. We do not provide a notice warning our users when they are leaving our website.
		</p>
	</li>
	<li>
		<br/>
		<h6>Information we collect<h6>
		<p>
			Deallr services include the collection, aggregation, analysis, and organization of email receipts and related information to provide users an integrated, actionable environment to manage and obtain maximum benefits from their purchasing activities. By registering for an account with Deallr, you are authorizing us to gather, parse, and retain data and information from emails you receive that are associated with your online and offline purchases and shopping, as necessary to deliver and support our services. Deallr is able to offer a free service to consumers by aggregating and analyzing the data you supply to us as a registered user. Deallr does not, however, use your PII for the purposes of monetization (see Section 3).
			<br/>
			Deallr collects PII when you register. In registering with Deallr, you may also provide information necessary to use Deallr, such as the login credentials for your mail, social networking, or other Internet accounts that you link to Deallr. We may also collect PII from you in other ways, such as contacts with our customer-support team.
			<br/>
			Non-PII Collection. Whenever you visit Deallr, Deallr also receives and records information on our server logs from your browser, including your IP address, Deallr cookie information, and the pages you request, and relates it to the PII you provide. Deallr uses this information to provide our services, to improve our products and services, to contact you, to conduct research, and to develop and maintain anonymous or aggregated data and analytics.			
		</p>
	</li>
	<li>
		<br/>
		<h6>How we use your personal information<h6>
		<p>
			Our use of PII. We use PII for internal and service-related purposes only and we may use vendors and suppliers to allow us to offer Deallr. Deallr does not rent, sell, or share PII about you with other people or nonaffiliated companies for marketing purposes. While we do not rent, share, or sell PII to advertisers, we may allow access to other Deallr data to enable the delivery of marketing and offers that will be of greatest utility, relevance, value, and interest to you.
			<br/>
			Anonymous use and sharing. We may share with third parties anonymized information in the performance of marketing services, including evaluating market trends and/or under a joint marketing agreement to provide services that will be of particular interest and relevance to you. Such information will not include PII.
			<br/>
			Legal sharing for protection of us, you, and others. We may disclose PII to third parties who are: assisting us in protecting against or preventing actual or potential fraud, unauthorized transactions, claims or other liabilities, or to investigate potential fraudulent or questionable activities. We may disclose PII in response to legal process, for example, in response to a court order or a subpoena. We may disclose PII in response to a law enforcement agency's request, or where we believe it is necessary to investigate, prevent, or take action regarding illegal activities or suspected fraud, violations of our Terms of Service, or as we believe may be otherwise required by law.
			<br/>
			Merger or sale. If all or substantially all of Deallr or its assets are sold or transferred, PII and other information we have collected may be treated as an asset and transferred in accordance with this Policy.
			<br/>
			We reserve the right to send you certain communications relating to Deallr, such as service announcements and administrative messages that are considered part of your Deallr account.
			<br/>
			Cookies and related technologies. Deallr uses "cookies." Cookies are small text files that we place in visitors' computer browsers to store their preferences. Most browsers allow you to manage cookies including blocking and deleting them. If you block or delete our cookies, Deallr may not work as well or at all for you.
		</p>
	</li>
	<li>
		<br/>
		<h6>How we secure your personal information<h6>
		<p>
			Deallr limits access to your PII. We have put in place physical, electronic, and managerial procedures in an effort to safeguard and help prevent unauthorized access, maintain data security, and use correctly the PII we collect from you.
			<br/>
			No data transmissions through the Internet or mobile devices, or even the physical transfer of information, can be guaranteed to be completely secure. We cannot eliminate fully all security risks associated with personal information and technical mistakes are possible. We do not ensure or warrant the security of any data or information you transmit to us and you do so at your own risk.
			<br/>
			If Deallr learns of a security systems breach, then we may attempt to notify you electronically. You agree that we may communicate with you electronically regarding security, privacy, and administrative issues. We may post a notice on our website if a security breach occurs. If this happens, you will need a web browser enabling you to view and access Deallr. We may also send an email to you at the email address you have provided to us. Depending on where you live, you may have a legal right to receive notice of a security breach in writing. To receive free written notice of a security breach (or to withdraw your consent from receiving electronic notice), you should notify us at: support@deallr.com.
		</p>
	</li>
	<li>
		<br/>
		<h6>International visitors<h6>
		<p>
			Deallr is hosted in and intended for use in the United States by U.S. residents. We may transfer your PII within Deallr including to any of our worldwide affiliates acting on our behalf and in accordance with this policy.
			<br/>
			If you are visiting from the European Union or other regions with laws governing data collection and use, please note that you are agreeing to the transfer of your personal information to the United States to Deallr. By providing your PII you consent to any transfer and processing in accordance with this Policy.
		</p>
	</li>
	<li>
		<br/>
		<h6>How to contact us<h6>
		<p>
			If you have questions or suggestions, please email Deallr at <a href="mailto:support@deallr.com">support@deallr.com</a>
		</p>
	</li>
	<li>
		<br/>
		<h6>To review or correct your personal information<h6>
		<p>
			Upon request, we will provide an individual with access to PII that we have collected about them (provided that they have given proof of identity). This information can be requested by sending us an email through the email link provided above or writing to us at the above address. This information can be corrected by sending us an email through the email link provided above or writing to us at the above address.
		</p>
	</li>
	<li>
		<br/>
		<h6>How we may update our privacy policy<h6>
		<p>
			From time to time, we may use PII for new, unanticipated uses not previously disclosed in our Privacy Policy. If our information practices change, we will immediately post any adjustments to our Policy on this website. The revised version usually will be effective at the time we post it; however, if the revised version includes a change that would be materially less restrictive on our use of your PII, we will provide you with 30 days' prior notice by posting notice of the change on the "Policy Updates" page of our website. If you are concerned about how your information is used, bookmark this page and check back periodically.
		</p>
	</li>
</ol>