<?php

	$tip = '<p class="tip-container">
				<img src="/resources/images/light_bulb.png" alt="Tip" />
				<span class="tip-message">Tip: Free your personal inbox from deals. Use the following dedicated Deallr address for deal signups.</span>
			</p>
			<div class="wrapper" id="user-deallr-address-container">
				<div id="user-deallr-address-label">Your personal Deallr address: </div>
				<div id="user-deallr-address">' . $this->deallr_address . '</div>
			</div>
	';
?>
<div class="content-box" id="<?= $this->wallet ? "user-wallet-deals" : "user-deals" ?>"><!-- Start Content Box -->
		
	<div class="content-box-content">
		
		<div class="tab-content default-tab" id="tab1"> <!-- This is the target div. id must match the href of this div's tab -->
			<?php if ($this->user_deals['deals']): 
				$all_none_select_container = '
					<div class="all-none-select-container">
						<span name="all" title="Select All" class="selector">All</span>
						<span class="separator">|</span>
						<span name="none" title="Unselect All" class="selector">None</span>
					</div>
				';
				
				$expand_collapse_selectors = '
					<img class="expand-collapse-indicator collapsed hidden" src="/resources/images/arrow_right_white.png" width="10px" height="10px" />
					<img class="expand-collapse-indicator expanded" src="/resources/images/arrow_down.png" width="10px" height="10px" />
				';
			?>
				<div id="sidebar">
					<div id="sidebar-wrapper"> <!-- Sidebar with logo and menu -->
						<h3 id="sidebar-title">Filters</h3>
						<ul id="main-filter">  <!-- Accordion Menu -->
							<li>
								<?= $all_none_select_container ?>
								<a href="#" class="filter-group current"> <!-- Add the class "current" to current menu item -->
									<?= $expand_collapse_selectors ?>
									Companies
								</a>
								<ul id="publisher-filter">
								</ul>
<!--
							</li>
								<li>
								<a href="#" class="filter-group">
									Discount %
								</a>
								<ul>
									<li>
										<div id="discount-per-slider"></div>
										<div id="discount-slider-values"></div>
									</li>
								</ul>
							</li>
							
							<li>
								<a href="#" class="filter-group">
									Expiry Date
								</a>
								<ul>
								</ul>
							</li>
							
-->
							<li>
								<?= $all_none_select_container ?>
								<a href="#" class="filter-group current">
									<?= $expand_collapse_selectors ?>
									Categories
								</a>
								<ul id="category-filter">
								</ul>
							</li>
	
						</ul> <!-- End #main-filter -->
					</div>
				</div> <!-- End #sidebar -->
				<div id="deals-sort-select-container">
					Organize by: 
					<select>
						<?php
							foreach ($this->sort_params as $key => $sort_param) {
								echo '<option value="sort-param-'.$key.'">'.$sort_param.'</option>';
							}
						?>
					</select>
				</div>
				<div id="deals-container">
					<div id="deals-filter-overlay" style="display: none;"><img src="<?= $this->baseUrl() ?>/resources/images/loading.gif" alt="Loading" /> Applying Filter...</div>
					<div id="deals-loading"><img src="<?= $this->baseUrl() ?>/resources/images/loading.gif" alt="Loading" /> Loading Deals...</div>
					<div id="filter-no-results" style="display: none;">No deals matching your filter conditions were found.</div>
				</div>
				<div id="load-more-deals-container">
					<a class="button white" id="load-more-deals">Load more..</a>
			 	</div>
				<script type="text/javascript">
					Application.__user_deals = <?= json_encode( $this->user_deals ); ?>;
					Application.__deals_obj = new Deals();
					Application.__deals_obj.init( Application.__user_deals, <?= $this->wallet ?> );
				</script>
			<?php elseif (!$this->user['hasSetupEmailAccounts'] && !$this->wallet) : ?>
				<p id="no-deals-msg-container">No email address found to fetch deals from. Please <a href="<?= $this->baseUrl(). '/account/add' ?>">add an email account</a> first.</p>
				<?= $tip ?>
			<?php elseif (isset($this->fetch_status) && $this->fetch_status == "inprogress" && !$this->wallet): ?>
				<p id="no-deals-msg-container"><img src="<?= $this->baseUrl() ?>/resources/images/loading-bar.gif" alt="Loading Bar" /><br/><br/>Deallr is currently fetching deals from your inbox. Please wait a few moments.</p>
				<?= $tip ?>
				<script type="text/javascript">
					var df = new DealFetcher();
					df.init();
				</script>
			<?php elseif (isset($this->fetch_status) && $this->fetch_status == "error" && !$this->wallet): ?>	
				<p id="no-deals-msg-container"><img src="<?= $this->baseUrl() ?>/resources/images/warning.png" class="warning-img" alt="Warning" />There was an error in reading deals from your inbox.</p>
			<?php else: ?>
				<p id="no-deals-msg-container">You currently do not have any deals<?= $this->wallet ? ' in your wallet. You can add your favorites from the <a href="'.$this->baseUrl().'/deals">Deals</a> page' : '' ?>.</p>
				<?= $tip ?>
		 	<?php endif; //user_deals ?>
			<div class="clearboth"></div>
		</div> <!-- End #tab1 -->
				
	</div> <!-- End .content-box-content -->
	
</div> <!-- End .content-box -->