    <div id="footer">
		<noscript> <!-- Show a notification if the user has disabled javascript -->
			<div class="notification error png_bg">
				<div>
					Javascript is disabled or is not supported by your browser. Please <a href="http://browsehappy.com/" title="Upgrade to a better browser">upgrade</a> your browser or <a href="http://www.google.com/support/bin/answer.py?answer=23852" title="Enable Javascript in your browser">enable</a> Javascript to navigate the interface properly.
				</div>
			</div>
		</noscript>      
    	<div id="footer_inner">
			<div class="one_half first"><!-- Start of one_third -->
				<ul id="footer_links">
					<li>&copy <?= date('Y')?> Deallr</li>
					<li><a href="<?= $this->baseUrl(); ?>/about">About</a></li>
					<li><a href="http://blog.deallr.com" target="_blank">Blog</a></li>
					<li><a href="<?= $this->baseUrl(); ?>/privacy">Privacy</a></li>
					<li><a href="<?= $this->baseUrl(); ?>/tos">Terms of Service</a></li>
					<li><a href="<?= $this->baseUrl(); ?>/contact">Contact</a></li>
				</ul>
	        </div><!-- End of one_third -->

			<div class="one_half aright"><!-- Start of one_third_last -->
				<ul class="social">
					<li>Connect with us on: </li>
					<li><a target="_blank" href="http://twitter.com/#!/deallr" class="fade" title="Follow us on Twitter">Twitter</a></li>
					<li><a target="_blank" href="http://www.facebook.com/pages/Deallr/286922524669951" class="fade" title="Like our page on Facebook">Facebook</a></li>
				</ul>
			</div><!-- End of one_third_last -->   
			<div class="clear">&nbsp;&nbsp;&nbsp;</div>
		</div><!-- End of footer_inner -->
	</div><!-- End of footer -->
	<script type="text/javascript">
	  var uvOptions = {};
	  (function() {
	    var uv = document.createElement('script'); uv.type = 'text/javascript'; uv.async = true;
	    uv.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'widget.uservoice.com/UlznK5JP9CsarJYrvucDJw.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(uv, s);
	  })();
	</script>	
</body>
</html>	