<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:og="http://ogp.me/ns#" xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
	<?php
		$default_title = 'Start Loving Deals Again'; 
		$default_image = 'http://dev.deallr.com/resources/images/logo.png';
	?>

	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta property="og:app_id" content="218435764843462" />
	<meta property="og:title" content="<?= isset($this->page_title) ? 'Deallr | Deal - ' . $this->page_title : $default_title ?>" />
	<meta property="og:image" content="<?= $default_image ?>" />
	<meta property="og:site_name" content="Deallr" />
	<meta property="og:type" content="deal"/>
	<?php
		if ($this->page_desc) {
			echo '<meta property="og:description" content="'.$this->page_desc.'"/>';
			echo '<meta property="og:url" content="http://'.$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'].'" />';
		}
	?>
	<meta property="fb:admins" content="100002376999672" />
	<meta property="fb:app_id" content="218435764843462" />
	
	<title>Deallr | <?= isset($this->page_title) ? 'Deal - ' . $this->page_title : $default_title ?></title>
		
	<!-- Reset Stylesheet -->
	<link rel="stylesheet" href="<?= $this->baseUrl(); ?>/resources/css/reset.css" type="text/css" media="screen" />
	<!-- Stylesheet Files -->
	<link href="<?= $this->baseUrl(); ?>/resources/css/main.css" rel="stylesheet" type="text/css" />
	<link href="<?= $this->baseUrl(); ?>/resources/css/superfish.css" rel="stylesheet" type="text/css" />
	
	<?php 
		if( isset($this->css) && is_array($this->css) )
		{
			echo implode("\n", $this->css);
		}
	?>
	
	<!-- JavaScript Files -->
	<!-- jQuery -->
	<script type="text/javascript" src="<?= $this->baseUrl(); ?>/resources/js/library/jquery-1.6.1.min.js"></script>
	<!-- jQuery UI -->
	<script type="text/javascript" src="<?= $this->baseUrl(); ?>/resources/js/library/jquery-ui-1.8.13.custom.min.js"></script>
	<!-- jQuery Plugins -->
	<script type="text/javascript" src="<?= $this->baseUrl(); ?>/resources/js/library/supersubs.js"></script>
	<script type="text/javascript" src="<?= $this->baseUrl(); ?>/resources/js/library/superfish.js"></script>
	<script type="text/javascript" src="<?= $this->baseUrl(); ?>/resources/js/scrolltopcontrol.js"></script>
	<script type="text/javascript" src="<?= $this->baseUrl(); ?>/resources/js/jquery.easing.1.3.js" charset="utf-8"></script>
	<!-- Internet Explorer .png-fix -->
	<!--[if IE 6]>
		<script type="text/javascript" src="<?= $this->baseUrl(); ?>/resources/js/library/DD_belatedPNG_0.0.7a.js"></script>
		<script type="text/javascript">
			DD_belatedPNG.fix('.png_bg, img, li');
		</script>
	<![endif]-->	
	<!-- Site JS -->
	<script type="text/javascript" src="<?= $this->baseUrl(); ?>/resources/js/landing.js"></script>
	<script type="text/javascript" src="<?= $this->baseUrl(); ?>/resources/js/custom.js"></script>
	<script type="text/javascript" src="<?= $this->baseUrl(); ?>/resources/js/utils/DeallrUtils.js"></script>		
	<?php 
		if( isset($this->js) && is_array($this->js) )
		{
			echo implode("\n", $this->js);
		}
	?>
	<script type="text/javascript"> 
	    $(document).ready(function(){ 
	        $("ul.sf-menu").supersubs({ 
	            minWidth:    12,   // minimum width of sub-menus in em units 
	            maxWidth:    45,   // maximum width of sub-menus in em units 
	            extraWidth:  1     // extra width can ensure lines don't sometimes turn over 
	                               // due to slight rounding differences and font-family 
	        }).superfish();  // call supersubs first, then superfish, so that subs are 
	                         // not display:none when measuring. Call before initialising 
	                         // containing tabs for same reason. 
	    });
		
		/*************************************************************************
		*************************  TIPSY SCRIPT LEAVE HERE!  *********************
		**************************************************************************/
		$(function() {
			$('#example-1').tipsy();
			
			$('#north').tipsy({gravity: 'n'});
			$('#south').tipsy({gravity: 's'});
			$('#east').tipsy({gravity: 'e'});
			$('#west').tipsy({gravity: 'w'});
			
			$('#auto-gravity').tipsy({gravity: $.fn.tipsy.autoNS});
			
			$('.fade').tipsy({fade: true});
			
			$('#example-custom-attribute').tipsy({title: 'id'});
			$('#example-callback').tipsy({title: function() { return this.getAttribute('original-title').toUpperCase(); } });
			$('#example-fallback').tipsy({fallback: "?" });
			
			$('#example-html').tipsy({html: true });			
		});
	</script>	
	<script type="text/javascript">
		Application = {};
		Application.__user_deals = {};
	</script>
	
	<?php if ($this->ga_id): ?>
		<script type="text/javascript">
			var _gaq = _gaq || [];
			_gaq.push(['_setAccount', "<?= $this->ga_id ?>"]);
			_gaq.push(['_trackPageview']);
			
			(function() {
				var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
				ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
				var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
			})();
		</script>	
	<?php endif; ?>
</head>
<body>