<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Deallr - Start Loving Deals Again</title>
	
	<!-- Reset Stylesheet -->
	<link rel="stylesheet" href="<?= $this->baseUrl(); ?>/resources/css/reset.css" type="text/css" media="screen" />
	<!-- Stylesheet Files -->
	<link href="/resources/css/main.css" rel="stylesheet" type="text/css" />
	<link href="/resources/css/superfish.css" rel="stylesheet" type="text/css" />
	
	<?php 
		if( isset($this->css) && is_array($this->css) )
		{
			echo implode("\n", $this->css);
		}
	?>
	
	<!-- JavaScript Files -->
	<!-- jQuery -->
	<script type="text/javascript" src="<?= $this->baseUrl(); ?>/resources/js/library/jquery-1.6.1.min.js"></script>
	<!-- jQuery UI -->
	<script type="text/javascript" src="<?= $this->baseUrl(); ?>/resources/js/library/jquery-ui-1.8.13.custom.min.js"></script>
	<script type="text/javascript" src="/resources/js/scrolltopcontrol.js"></script>
	<script type="text/javascript" src="/resources/js/jquery.easing.1.3.js" charset="utf-8"></script>
	<!-- Internet Explorer .png-fix -->
	<!--[if IE 6]>
		<script type="text/javascript" src="<?= $this->baseUrl(); ?>/resources/js/library/DD_belatedPNG_0.0.7a.js"></script>
		<script type="text/javascript">
			DD_belatedPNG.fix('.png_bg, img, li');
		</script>
	<![endif]-->	
	<!-- Site JS -->
	<script type="text/javascript" src="<?= $this->baseUrl(); ?>/resources/js/landing.js"></script>
	<script type="text/javascript" src="/resources/js/custom.js"></script>
	<script type="text/javascript" src="<?= $this->baseUrl(); ?>/resources/js/utils/DeallrUtils.js"></script>		
	<script type="text/javascript" src="<?= $this->baseUrl(); ?>/resources/js/Deals.js"></script>
	<?php 
		if( isset($this->js) && is_array($this->js) )
		{
			echo implode("\n", $this->js);
		}
	?>
	<script type="text/javascript">
		Application = {};
		Application.__user_deals = {};
	</script>	
</head>
<body>