<?php 
	if(isset($this->controller) && in_array($this->controller, array('deals', 'account', 'wallet'))): ?>
			<ul class="sf-menu">
				<li><a href="<?= $this->controller == 'deals' ? '' : $this->baseUrl().'/deals' ?>" class="<?= $this->controller == 'deals' ? 'active' : '' ?>"><div style="position:relative;" id="deals-nav">Deals</div></a></li>
				<li><a href="<?= $this->controller == 'wallet' ? '' : $this->baseUrl().'/wallet' ?>" class="<?= $this->controller == 'wallet' ? 'active' : '' ?>">Wallet</a></li>
				<li><a><img height="26px" width="26px" class="profile-pic" src="<?= 'https://graph.facebook.com/'.$this->user['fbUserId'].'/picture' ?>" alt="Profile Picture" /><?= $this->user['fbFullName'] ?></a>
					<ul>
					<li><a href="/account/add">Settings</a></li>
					<li><a href="/sign-out">Log Out</a></li>
					</ul>
				</li>
	  		</ul><!-- this is the end of the unordered list -->
<?php else: ?>
			<ul class="sf-menu">
				<li><a class="active" href="/landing">Home</a></li>
				<li><a href="http://blog.deallr.com/" target="_blank">Blog</a></li>
				<li><a href="#">Contact</a></li>
	  		</ul><!-- this is the end of the unordered list -->
<?php endif; ?>
