<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Deallr - Start Loving Deals Again</title>
<!-- Reset Stylesheet -->
<link rel="stylesheet" href="<?= $this->baseUrl(); ?>/resources/css/reset.css" type="text/css" media="screen" />
<!-- Stylesheet Files -->
<link href="/resources/css/main.css" rel="stylesheet" type="text/css" />
<link href="/resources/css/superfish.css" rel="stylesheet" type="text/css" />
<!-- JavaScript Files -->
<!-- jQuery -->
<script type="text/javascript" src="<?= $this->baseUrl(); ?>/resources/js/library/jquery-1.6.1.min.js"></script>
<!-- jQuery UI -->
<script type="text/javascript" src="<?= $this->baseUrl(); ?>/resources/js/library/jquery-ui-1.8.13.custom.min.js"></script>
<!-- Site JS -->
<script type="text/javascript" src="<?= $this->baseUrl(); ?>/resources/js/landing.js"></script>
<script type="text/javascript" src="/resources/js/custom.js"></script>
<script type="text/javascript" src="/resources/js/scrolltopcontrol.js"></script>
<script type="text/javascript" src="/resources/js/jquery.easing.1.3.js" charset="utf-8"></script>
</head>
<body>
<div id="header_bar"><!-- Start of header_bar -->
    <div id="header_content"><!-- Start of header_content -->
		<div id="top_logo"><!-- Start of top_logo -->
      		<img src="<?= $this->baseUrl(); ?>/resources/images/logo.png" alt="Deallr logo" width="200px" height="164px" alt="qop logo" />
		</div><!-- End of top_logo -->

		<div id="top_menu"><!-- Start of top_menu -->

			<ul class="sf-menu">
				<li><a class="active" href="index.html">Home</a></li>
				<li><a href="http://blog.deallr.com/" target="_blank">Blog</a></li>
				<li><a href="#">Contact</a></li>
	  		</ul><!-- this is the end of the unordered list -->
		</div><!-- End of top_menu -->
	</div><!-- End of header_content -->
</div><!-- End of header_bar -->

	<h1 style="font-size:46px;text-align:center;">Deal management made easy and fun.</h1>
	<div style="background:#F2F2F2;border:1px solid #EEE;border-radius:6px;margin:10px auto;width:600px;padding:175px 0;color:#AAA;text-align:center;">Video or Screenshot Here</div>
	<div class="message_bar"><!-- Start of message_bar -->
		<div class="wrapper">
			<div class="message_content" style="text-align:right;float:none;">Join Deallr now. Its free.
				<div class="message_button" style="margin-top: -26px; margin-left: 20px;">
					<div class="buttonbackground"><a href="#" class="button blue bigrounded" id="fb-login">Login with Facebook</a></div>
				</div>
			</div>
        </div>
	</div><!-- End of message_bar -->
	
	<div class="wrapper">
	<div class="shaded_bar"></div>

		<div class="one_third_center"><!-- Start of one_third -->
			<h3>All your Deals in one place</h3>
			<p>Deallr allows you to manage all your deals from one place. Subscribe/unsubscribe to all major retailers and deal websites.</p>
			<!-- <a href="#" class="button white big">Read More</a> -->
		</div><!-- End of one_third -->

		<div class="one_third_center"><!-- Start of one_third -->
			<h3>Free your personal email inbox</h3>
			<p>Deallr gives you an @deallr.com email address just for deals signup. You no longer have to give away your personal email address.</p>
			<!-- <a href="#" class="button white big">Read More</a> -->
		</div><!-- End of one_third -->


		<div class="column-last_center"><!-- Start of one_third_last -->
			<h3>Add Deals to Wallet</h3>
			<p>Add deals to your digital wallet to access later. Deallr also learns your preferences based on your wallet deals.</p>
			<!-- <a href="#" class="button white big">Read More</a> -->
		</div><!-- End of one_third_last -->
	</div><!-- end of wrapper -->

	<div class="wrapper" style="margin-top: 20px;">

		<div class="one_third_center"><!-- Start of one_third -->
			<h3>Get Personalized Deals</h3>
			<p>Deallr shows you only the deals that you are interested in based on your preferences.</p>
			<!-- <a href="#" class="button white big">Read More</a> -->
		</div><!-- End of one_third -->

		<div class="one_third_center"><!-- Start of one_third -->
			<h3>Deal Ending Reminders</h3>
			<p>Deallr reminds you when any of your favorite deals is about to expire, so you never miss them.</p>
			<!-- <a href="#" class="button white big">Read More</a> -->
		</div><!-- End of one_third -->

		<div class="column-last_center"><!-- Start of one_third_last -->
			<h3>Popular Deals</h3>
			<p>Deallr shows you the popular deals each day along with your own personal list of deals.</p>
			<!-- <a href="#" class="button white big">Read More</a> -->
		</div><!-- End of one_third_last -->
	</div>
		
		
    
    <div class="message_bar" style="background:#F1EFED; height:150px; border-top:1px solid #D5D5D7;"><!-- Start of menu_bar -->
    	<div class="wrapper">
			<div class="message_content" style="float: none; text-align: center; width: 100%; padding: 0;">Deallr supports deals from major retailers and deal web sites.</div>
			<div id="retailers-logos">
				<ul>
					<li><a href="#"><img src="http://www1.macys.com/img/nav/co_macysLogo3.gif" alt="image 1" /></a><li>
					<li><a href="#"><img src="http://www.pier1.com/Portals/0/logo.gif" alt="image 1" /></a><li>
					<li><a href="#"><img src="http://www.apeainthepod.com/images/Site/pea_logo_052610.gif" alt="image 1" /></a><li>
					<li><a href="#"><img src="http://shop.guess.com/content/guess/images/header/guessLogo.png" alt="image 1" /></a><li>
				</ul>
			</div>
        </div>
	</div><!-- Start of menu_bar -->
    
    <div id="footer">    
    	<div id="footer_inner">
			<div class="footer_one_third"><!-- Start of one_third -->
				<h4>About Deallr</h4>
				<p>Deallr is a personalized deal management app. <br/>It fetches all your deals and presents them in a single concise view. Deallr also gives each user an email address dedicated for deals allowing you to free your inbox from deals.</p>
				<p>It enables you to get deals when you want them rather than the reverse.</p>
				<p><a href="#">Continue reading...</a></p>
	        </div><!-- End of one_third -->

			<div class="footer_one_third"><!-- Start of one_third -->
				<ul>
					<li><a href="http://blog.deallr.com/" target="_blank">Blog</a></li>
					<li><a>Help</a></li>
					<li><a>Media</a></li>
					<li><a>Jobs</a></li>
					<li><a>Privacy</a></li>
					<li><a>Terms &amp; Conditions</a></li>
				</ul>
	        </div><!-- End of one_third -->

			<div class="footer_one_third_last"><!-- Start of one_third_last -->
				<h4>Get news and updates from Deallr</h4>
				<!-- start of newsletter signup wrapper -->
				<div class="contact_wrapper">
					<form action="#" method="post">
						<input name="search" id="search" type="text" class="default-value input-textarea" value="Your email address"  onblur="if (this.value=='') {this.value='Your email address'; }" onfocus="if (this.value=='Your email address') {this.value=''; }" />
						<input style="margin: 10px 0 25px;" name="Submit" id="submit" type="submit" value="Sign me up for the newsletter" class="button highlight" />
					</form>
				</div><!-- end of newsletter signup wrapper -->
			
				<div class="clear"></div>
			
				<h4>Follow Us</h4>
				<ul class="social">
					<li><a href="#" class='fade' title="twitter"><img src="/resources/images/twitter.png" width="35" height="35" alt="twitter" /></a></li>
					<li><a href="#" class='fade' title="linkedin"><img src="/resources/images/linkedin.png" width="35" height="35" alt="linkedin" /></a></li>
					<li><a href="#" class='fade' title="stumbleupon"><img src="/resources/images/stumbleupon.png" width="35" height="35" alt="stumbleupon" /></a></li>
					<li><a href="#" class='fade' title="facebook"><img src="/resources/images/facebook.png" width="35" height="35" alt="facebook" /></a></li>
				</ul>
			</div><!-- End of one_third_last -->   
			<div class="clear">&nbsp;&nbsp;&nbsp;</div>
		</div><!-- End of footer_inner -->
	</div><!-- End of footer -->
</body>
</html>