<?php
	echo $this->partial('_header.phtml', array(
		'css'=> array('<link rel="stylesheet" href="'.$this->baseUrl().'/resources/css/landing.css" type="text/css" media="screen" />'), 
		'ga_id' => $this->ga_id
	));
	echo $this->partial('_topHeader.phtml', array('controller' => $this->controller, 'action' => $this->action));
?>
	<div class="wrapper">
		<h1 id="landing-tag-line-container">Start <img src="<?= $this->baseUrl(); ?>/resources/images/love.png" alt="love" />ing deals again.</h1>
		<div id="landing-img-container"><img src="<?= $this->baseUrl(); ?>/resources/images/landing-final.png" alt="landing image" /></div>
		<div id="landing-fb-login">
			<span class="FBConnectButton FBConnectButton_Small">
				<span id="fb-login" class="FBConnectButton_Text">Login with Facebook</span>
			</span>
		</div>
	</div>
	
	<div class="wrapper">
		<div class="shaded_bar"></div>
		<div class="one_third_center"><!-- Start of one_third -->
			<a href="#"><img src="<?= $this->baseUrl(); ?>/resources/images/badge1.jpg" width="280" height="172" alt="badge 1"></a>		
			<h3>Discover deals like never before</h3>
			<p>Don't miss a good deal again. Use advanced filters to zero in on the best deals. Forget searching through thousands of emails.</p>
			<!-- <a href="#" class="button white big">Read More</a> -->
		</div><!-- End of one_third -->

		<div class="one_third_center"><!-- Start of one_third -->
			<a href="#"><img src="<?= $this->baseUrl(); ?>/resources/images/badge4.jpg" width="280" height="172" alt="badge 2"></a>
			<h3>Free your personal email inbox</h3>
			<p>Deallr gives you an @deallr.com email address just for deals. You no longer have to give away your personal email address.</p>
			<!-- <a href="#" class="button white big">Read More</a> -->
		</div><!-- End of one_third -->


		<div class="column-last_center"><!-- Start of one_third_last -->
			<a href="#"><img src="<?= $this->baseUrl(); ?>/resources/images/badge3.jpg" width="280" height="172" alt="badge 3"></a>
			<h3>Deals from major retailers</h3>
			<p>Deallr allows you to manage all your deals from one place. Subscribe/unsubscribe to all major retailers and deal websites.</p>			
			<!-- <a href="#" class="button white big">Read More</a> -->
		</div><!-- End of one_third_last -->
	</div><!-- end of wrapper -->
<?php echo $this->partial('_footer.phtml'); ?>