<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
 
	<head>
		
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
		
		<title>Deallr - Start Loving Deals Again</title>
		
		<!--                       CSS                       -->
	  
		<!-- Reset Stylesheet -->
		<link rel="stylesheet" href="<?= $this->baseUrl(); ?>/resources/css/reset.css" type="text/css" media="screen" />
	  
		<!-- Main Stylesheet -->
		<link rel="stylesheet" href="<?= $this->baseUrl(); ?>/resources/css/style.css" type="text/css" media="screen" />
		
		<!-- Invalid Stylesheet. This makes stuff look pretty. Remove it if you want the CSS completely valid -->
		<link rel="stylesheet" href="<?= $this->baseUrl(); ?>/resources/css/invalid.css" type="text/css" media="screen" />	
		
		<link rel="stylesheet" href="<?= $this->baseUrl(); ?>/resources/css/red.css" type="text/css" media="screen" />  

		<link rel="stylesheet" href="<?= $this->baseUrl(); ?>/resources/css/smoothness/jquery-ui-1.8.13.custom.css" type="text/css" media="screen" />  

		<!-- Colour Schemes
	  
		Default colour scheme is green. Uncomment prefered stylesheet to use it.
		
		<link rel="stylesheet" href="<?= $this->baseUrl(); ?>/resources/css/blue.css" type="text/css" media="screen" />
		
	 
		-->
		
		<!-- Internet Explorer Fixes Stylesheet -->
		
		<!--[if lte IE 7]>
			<link rel="stylesheet" href="<?= $this->baseUrl(); ?>/resources/css/ie.css" type="text/css" media="screen" />
		<![endif]-->
		
		<!--                       Javascripts                       -->
  
		<!-- jQuery -->
		<script type="text/javascript" src="<?= $this->baseUrl(); ?>/resources/js/library/jquery-1.6.1.min.js"></script>
		
		<!-- jQuery UI -->
		<script type="text/javascript" src="<?= $this->baseUrl(); ?>/resources/js/library/jquery-ui-1.8.13.custom.min.js"></script>
		
		<!-- jQuery Configuration -->
		<script type="text/javascript" src="<?= $this->baseUrl(); ?>/resources/js/library/simpla.jquery.configuration.js"></script>
		
		<!-- Facebox jQuery Plugin -->
		<script type="text/javascript" src="<?= $this->baseUrl(); ?>/resources/js/library/facebox.js"></script>
		
		<!-- jQuery WYSIWYG Plugin -->
		<!-- <script type="text/javascript" src="<?= $this->baseUrl(); ?>/resources/js/library/jquery.wysiwyg.js"></script> -->

		<!-- Site JS -->
		<script type="text/javascript" src="<?= $this->baseUrl(); ?>/resources/js/utils/DeallrUtils.js"></script>		
		<script type="text/javascript" src="<?= $this->baseUrl(); ?>/resources/js/Deals.js"></script>
		
		<script type="text/javascript">
			Application = {};
			Application.__user_deals = {};
		</script>
		
		<!-- Internet Explorer .png-fix -->
		
		<!--[if IE 6]>
			<script type="text/javascript" src="<?= $this->baseUrl(); ?>/resources/js/library/DD_belatedPNG_0.0.7a.js"></script>
			<script type="text/javascript">
				DD_belatedPNG.fix('.png_bg, img, li');
			</script>
		<![endif]-->
		
	</head>
  
	<body><div id="body-wrapper"> <!-- Wrapper for the radial gradient background -->
		
		<div id="page-header">
			<h1 style="display:none;">Deallr</h1>
			<a href="#"><img id="logo" src="<?= $this->baseUrl(); ?>/resources/images/logo.png" alt="Deallr logo" /></a>
			<p id="page-intro">Start Loving Deals Again!</p>
		</div>
	
		<div id="main-content"> <!-- Main Content Section with everything -->
			
			<noscript> <!-- Show a notification if the user has disabled javascript -->
				<div class="notification error png_bg">
					<div>
						Javascript is disabled or is not supported by your browser. Please <a href="http://browsehappy.com/" title="Upgrade to a better browser">upgrade</a> your browser or <a href="http://www.google.com/support/bin/answer.py?answer=23852" title="Enable Javascript in your browser">enable</a> Javascript to navigate the interface properly.
					</div>
				</div>
			</noscript>
			
			<div class="clear"></div> <!-- End .clear -->
			
			<div class="content-box"><!-- Start Content Box -->
				
				<div class="content-box-header">
					
					<ul class="content-box-tabs">
						<li><a href="#tab1" class="default-tab">My Deals</a></li> <!-- href must be unique and match the id of target div -->
						<li><a href="#tab2">Popular</a></li>
					</ul>
					
					<div class="clear"></div>
					
				</div> <!-- End .content-box-header -->
				
				<div class="content-box-content">
					
					<div class="tab-content default-tab" id="tab1"> <!-- This is the target div. id must match the href of this div's tab -->
						
					<?php echo $this->layout()->content; ?>
					</div> <!-- End #tab1 -->
					
					<div class="tab-content" id="tab2">
					
						<form action="" method="post">
							
							<fieldset> <!-- Set class to "column-left" or "column-right" on fieldsets to divide the form into columns -->
								<p>
									<label>COMING SOON</label>
								</p>
							</fieldset>
							
							<div class="clear"></div><!-- End .clear -->
							
						</form>
						
					</div> <!-- End #tab2 -->        
					
				</div> <!-- End .content-box-content -->
				
			</div> <!-- End .content-box -->
			
			<div class="clear"></div>
			
			<div id="footer">
				&#169; Copyright <?= date('Y') ?> Deallr
			</div><!-- End #footer -->
			
		</div> <!-- End #main-content -->
		
	</div>
	
	</body>
  
</html>