<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
 
	<head>
		
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
		
		<title>Deallr - Start Loving Deals Again</title>
		
		<!--                       CSS                       -->
	  
		<!-- Reset Stylesheet -->
		<link rel="stylesheet" href="<?= $this->baseUrl(); ?>/resources/css/reset.css" type="text/css" media="screen" />
	  
		<!-- Main Stylesheet -->
		<link rel="stylesheet" href="<?= $this->baseUrl(); ?>/resources/css/style.css" type="text/css" media="screen" />
		
		<!-- Invalid Stylesheet. This makes stuff look pretty. Remove it if you want the CSS completely valid -->
		<link rel="stylesheet" href="<?= $this->baseUrl(); ?>/resources/css/invalid.css" type="text/css" media="screen" />	
		

		<link rel="stylesheet" href="<?= $this->baseUrl(); ?>/resources/css/smoothness/jquery-ui-1.8.13.custom.css" type="text/css" media="screen" />  

		<!-- Internet Explorer Fixes Stylesheet -->
		
		<!--[if lte IE 7]>
			<link rel="stylesheet" href="<?= $this->baseUrl(); ?>/resources/css/ie.css" type="text/css" media="screen" />
		<![endif]-->
		
		<!--                       Javascripts                       -->
  
		<!-- jQuery -->
		<script type="text/javascript" src="<?= $this->baseUrl(); ?>/resources/js/library/jquery-1.6.1.min.js"></script>
		
		<!-- jQuery UI -->
		<script type="text/javascript" src="<?= $this->baseUrl(); ?>/resources/js/library/jquery-ui-1.8.13.custom.min.js"></script>
		
		<!-- jQuery Configuration -->
		<script type="text/javascript" src="<?= $this->baseUrl(); ?>/resources/js/library/simpla.jquery.configuration.js"></script>
		
		<!-- Facebox jQuery Plugin -->
		<script type="text/javascript" src="<?= $this->baseUrl(); ?>/resources/js/library/facebox.js"></script>
		
		<!-- jQuery WYSIWYG Plugin -->
		<!-- <script type="text/javascript" src="<?= $this->baseUrl(); ?>/resources/js/library/jquery.wysiwyg.js"></script> -->

		<!-- Site JS -->
		<script type="text/javascript" src="<?= $this->baseUrl(); ?>/resources/js/utils/DeallrUtils.js"></script>		
		<script type="text/javascript" src="<?= $this->baseUrl(); ?>/resources/js/Deals.js"></script>
		
		<script type="text/javascript">
			Application = {};
			Application.__user_deals = {};
		</script>
		
		<!-- Internet Explorer .png-fix -->
		
		<!--[if IE 6]>
			<script type="text/javascript" src="<?= $this->baseUrl(); ?>/resources/js/library/DD_belatedPNG_0.0.7a.js"></script>
			<script type="text/javascript">
				DD_belatedPNG.fix('.png_bg, img, li');
			</script>
		<![endif]-->
		
	</head>
  
	<body id="login">
		
		<div id="login-wrapper" class="png_bg">
			<div id="login-top">
			
				<h1>Login to Deallr</h1>
			</div> <!-- End #logn-top -->
			<div id="login-content">
				<form action="/index" method="POST" enctype="application/x-www-form-urlencoded">
					<p>
						<label>Username</label>
						<input class="text-input" type="text" name="u" />
					</p>
					<div class="clear"></div>
					<p>
						<label>Password</label>
						<input class="text-input" type="password" name="p" />
					</p>
					<div class="clear"></div>
					<p id="remember-password">
						<input type="checkbox" />Remember me
					</p>
					<div class="clear"></div>
					<p>
						<input class="button" type="submit" value="Sign In" />
					</p>
				</form>
			</div> <!-- End #login-content -->
		</div> <!-- End #login-wrapper -->
  </body>
</html>